AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - 'bin/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'Guardfile'
    - 'Gemfile'

Metrics/MethodLength:
  Max: 20

Metrics/LineLength:
  Max: 100

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/MultilineMethodCallBraceLayout:
  EnforcedStyle: new_line
